---
sudo: required
notifications:
  slack:
    on_failure: always

matrix:
  fast_finish: true
  include:
     

# https://learn.hashicorp.com/tutorials/terraform/install-cli
    - name: "deploy terraform w homebrew on macOS 10.15.7 osx xcode12.2 "
      os: osx
      osx_image:
        - xcode12.2 #macOS 10.15.7
      addons:
        homebrew:
          taps: hashicorp/tap
          packages:
          - terraform    
          update: true
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - python --version
        - pip install -r requirements.txt
      script:
      - terraform -help
      - terraform -install-autocomplete 
      after_success:
        - deactivate        

# https://learn.hashicorp.com/tutorials/terraform/install-cli
    - name: "deploy terraform wo homebrew on macOS 10.15.7 osx xcode12.2"
      os: osx
      osx_image:
        - xcode12.2 #macOS 10.15.7
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - python --version
        - pip install -r requirements.txt
      script:
      - brew tap hashicorp/tap
      - brew install hashicorp/tap/terraform
      - terraform -help
      - terraform -install-autocomplete 
      after_success:
        - deactivate 

