---

- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.longname }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED {{ item.name }}"
  with_items:
    - { ip: 172.28.128.12, longname: terraformsandbox01.local, name: terraformsandbox01}
    - { ip: 172.28.128.15, longname: terraformsandbox02.local, name: terraformsandbox02}
    - { ip: 172.28.128.16, longname: terraformsandbox03.local, name: terraformsandbox03}
  when: add_host_entries

- name: Add mappings to /etc/resolv.conf
  blockinfile:
    path: /etc/resolv.conf
    block: |
      {{ item.name }} {{ item.ip }}
    marker: "# {mark} ANSIBLE MANAGED {{ item.ip }}"
  with_items:
    - { name: nameserver, ip: 8.8.8.8}
  when: add_host_entries
